name: Create Release

# Create XCFramework when a version is tagged
on:
  push:
    tags:1.0

jobs:
  create_release:
    name: Create Release
    runs-on: macos-latest
    steps:

      - uses: actions/checkout@main

      - name: swift-create-xcframework
        uses: unsignedapps/swift-create-xcframework@v2.1.0


      # Create a release
      # Upload those artifacts to the release
